try test

diff --git a/.github/workflows/refactor-hpc-development-image.yaml b/.github/workflows/refactor-hpc-development-image.yaml
--- a/.github/workflows/refactor-hpc-development-image.yaml
+++ b/.github/workflows/refactor-hpc-development-image.yaml
@@ -266,26 +266,6 @@ jobs:
             ${{ inputs.mpi_build_args }}
           target: final
 
-      # - name: Base OS + Compiler + MPI
-      #   uses: docker/build-push-action@v6
-      #   with:
-      #     push: true
-      #     tags: ${{ env.CI_IMAGE_TAG }},${{ env.CI_IMAGE_TAG_DEVEL }}
-      #     cache-from: type=registry,ref=benjaminkirk/gh-ci-cache-${{ inputs.os }}:cache-${{ inputs.arch }}-${{env.INPUTS_SHA }}
-      #     cache-to: type=registry,ref=benjaminkirk/gh-ci-cache-${{ inputs.os }}:cache-${{ inputs.arch }}-${{ env.INPUTS_SHA }},mode=max
-      #     context: containers/refactor
-      #     file: containers/refactor/Dockerfile
-      #     build-args: |
-      #       BASE_OS=${{ inputs.os }}
-      #       COMPILERS_PREREQ=${{ inputs.conda && 'miniforge' || inputs.os }}
-      #       ${{ inputs.compiler_build_args }}
-      #       ${{ inputs.gpu_build_args }}
-      #       ${{ inputs.mpi_build_args }}
-      #       MPI_PREREQ=${{ inputs.gpu == 'nogpu' && 'compilers' || inputs.gpu }}
-      #       FINAL_TARGET=fftlibs
-      #       ${{ inputs.extra_build_args }}
-      #     target: final
-
     outputs:
       CI_IMAGE_TAG: ${{ steps.tags.outputs.CI_IMAGE_TAG }}
       PUBLISH_IMAGE_TAG: ${{ steps.tags.outputs.PUBLISH_IMAGE_TAG }}
@@ -293,79 +273,81 @@ jobs:
 
 
 
-  # test-image:
-  #   name: Test Image
-  #   needs: build-image
-  #   runs-on: ${{ inputs.runner }}
+  test-image:
+    name: Test Image
+    needs: build-image
+    runs-on: ${{ inputs.runner }}
 
-  #   defaults:
-  #     run:
-  #       shell: bash -elo pipefail {0}
+    defaults:
+      run:
+        shell: bash -elo pipefail {0}
 
-  #   container:
-  #     image: ${{ needs.build-image.outputs.CI_IMAGE_TAG }}
+    container:
+      image: ${{ needs.build-image.outputs.CI_IMAGE_TAG }}
 
-  #   if: ${{ inputs.test }}
-  #   steps:
-  #     - name: Download Build Artifacts
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: image-metadata-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.mpi }}-${{ inputs.gpu }}
-  #         merge-multiple: true
+    if: ${{ inputs.test }}
+    steps:
+      - name: Download Build Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: image-metadata-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.mpi }}-${{ inputs.gpu }}
+          merge-multiple: true
 
-  #     - name: Augment Environment with Artifact Results
-  #       id: tags
-  #       run: |
-  #         cat tags.sh >> ${GITHUB_ENV}
-  #         cat tags.sh >> ${GITHUB_OUTPUT}
+      - name: Augment Environment with Artifact Results
+        id: tags
+        run: |
+          cat tags.sh >> ${GITHUB_ENV}
+          cat tags.sh >> ${GITHUB_OUTPUT}
 
-  #     - name: Interrogate Runtime Environment
-  #       run: |
-  #         pwd
-  #         ls
-  #         find -type d
-  #         env | sort
-  #         cat /container/config_env.sh
-  #         df -h
-  #         ls -l /glade/ || echo "No /glade on this runner?!!"
-  #         cat /etc/os-release 2>/dev/null || true
-  #         uname -a
-  #         lscpu
-  #         find /usr /container -name "libcuda.so.*" -o -name "nvidia-smi" -o -name "libnvidia-ml.so*"
-  #         [ -d "${CUDA_STUBDIR}" ] && rm -rf ${CUDA_STUBDIR}
-  #         which nvidia-smi 2>/dev/null && nvidia-smi 2>/dev/null || echo "nvidia-smi not found."
-  #         echo && echo && echo
-  #         echo '----------------------------------------------------------------'
-  #         echo && echo && echo
-  #         echo CI_IMAGE_TAG=${{ env.CI_IMAGE_TAG }}
-  #         echo PUBLISH_IMAGE_TAG=${{ env.PUBLISH_IMAGE_TAG }}
-  #         echo INPUTS_SHA=${{ env.INPUTS_SHA }}
-  #         echo
-  #         echo "CC=${CC}"
-  #         echo "CXX=${CXX}"
-  #         echo "FC=${FC}"
-  #         echo "F77=${F77}"
-  #         echo
-  #         echo "CFLAGS=${CFLAGS}"
-  #         echo "CPPFLAGS=${CPPFLAGS}"
-  #         echo "CXXFLAGS=${CXXFLAGS}"
-  #         echo "FCFLAGS=${FCFLAGS}"
-  #         echo "F77FLAGS=${F77FLAGS}"
-  #         export CC CXX FC F77 CFLAGS CXXFLAGS FCFLAGS F77FLAGS CPPFLAGS
-  #         conda --version 2>/dev/null || echo " --> no conda in this container"
-  #         which mpicc
-  #         mpicc --version 2>/dev/null || true
+      - name: Interrogate Runtime Environment
+        run: |
+          pwd
+          ls
+          find -type d
+          env | sort
+          cat /container/config_env.sh
+          df -h
+          ls -l /glade/ || echo "No /glade on this runner?!!"
+          cat /etc/os-release 2>/dev/null || true
+          uname -a
+          lscpu
+          #find /usr /container -name "libcuda.so.*" -o -name "nvidia-smi" -o -name "libnvidia-ml.so*"
+          #[ -d "${CUDA_STUBDIR}" ] && rm -rf ${CUDA_STUBDIR}
+          #which nvidia-smi 2>/dev/null && nvidia-smi 2>/dev/null || echo "nvidia-smi not found."
+          echo && echo && echo
+          echo '----------------------------------------------------------------'
+          echo && echo && echo
+          echo CI_IMAGE_TAG=${{ env.CI_IMAGE_TAG }}
+          echo PUBLISH_IMAGE_TAG=${{ env.PUBLISH_IMAGE_TAG }}
+          echo INPUTS_SHA=${{ env.INPUTS_SHA }}
+          echo
+          echo "CC=${CC}"
+          echo "CXX=${CXX}"
+          echo "FC=${FC}"
+          echo "F77=${F77}"
+          echo
+          echo "CFLAGS=${CFLAGS}"
+          echo "CPPFLAGS=${CPPFLAGS}"
+          echo "CXXFLAGS=${CXXFLAGS}"
+          echo "FCFLAGS=${FCFLAGS}"
+          echo "F77FLAGS=${F77FLAGS}"
+          export CC CXX FC F77 CFLAGS CXXFLAGS FCFLAGS F77FLAGS CPPFLAGS
+          conda --version 2>/dev/null || echo " --> no conda in this container"
+          which mpicc
+          mpicc --version 2>/dev/null || true
 
-  #     - name: MPI+OpenMP Hello World
-  #       run: |
-  #         mpicxx -o ./hello_world_mpi /container/extras/hello_world_mpi.C -fopenmp
-  #         ldd ./hello_world_mpi
-  #         export OMP_NUM_THREADS=2
-  #         mpiexec -n 2 ${{ matrix.extra_mpiexec_args }} ./hello_world_mpi || true
+      - name: MPI+OpenMP Hello World
+        continue-on-error: false
+        run: |
+          mpicxx -o ./hello_world_mpi /container/extras/hello_world_mpi.C -fopenmp
+          ldd ./hello_world_mpi
+          export OMP_NUM_THREADS=2
+          mpiexec -n 2 ${{ matrix.extra_mpiexec_args }} ./hello_world_mpi
 
-  #     - name: OSU MPI Benchmarks
-  #       run: |
-  #         /container/extras/build_osu-micro-benchmarks.sh
+      - name: OSU MPI Benchmarks
+        continue-on-error: false
+        run: |
+          /container/extras/build_osu-micro-benchmarks.sh
 
   #     - name: DART
   #       continue-on-error: true
